name: Promotion

on:
  push:
    tags:
    - prod-*

env:
  GOOGLECLOUD_REGION: "asia-northeast1"
  DELIVERY_PIPELINE: "my-pipeline"

jobs:
  promotion:
    name: Promotion
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
        service_account: "sa-github@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Promote a release
      run: gcloud deploy releases promote --release "git-${GITHUB_SHA::7}" --region ${{ env.GOOGLECLOUD_REGION }} --delivery-pipeline ${{ env.DELIVERY_PIPELINE }} --annotations "tag=${GITHUB_REF#refs/tags/},author=${GITHUB_ACTOR},date=$(date '+%Y-%m-%d %H:%M:%S')"
