name: Release

on:
  push:
    branches:
      - main

env:
  GOOGLECLOUD_REGION: "asia-northeast1"
  DELIVERY_PIPELINE: "my-pipeline"
  SKAFFOLD_MINOR_VERSION: "2.2.0"

jobs:
  test-code:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dart lang
      uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get
      working-directory: src
    - name: Verify formatting
      run: dart format — output=none — set-exit-if-changed .
      working-directory: src
    - name: Analyze project source
      run: dart analyze
      working-directory: src
    - name: Run tests
      run: dart test
      working-directory: src

  test-template:
    name: Test templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold && sudo mv skaffold /usr/local/bin
        skaffold version
    - name: Rendering
      run: |
        skaffold render --digest-source='none' -o dev.yaml
        skaffold render --digest-source='none' -o prod.yaml --profile prod
    - name: Kubeval k8s manifests
      uses: azure/k8s-lint@v2.0
      with:
        manifests: |
            dev.yaml
            prod.yaml

  release:
    name: Release
    needs:
      - test-code
      - test-template
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
        service_account: "sa-github@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup credential helper
      run: gcloud auth configure-docker "${{ env.GOOGLECLOUD_REGION}}-docker.pkg.dev"

    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v${{ env.SKAFFOLD_MINOR_VERSION }}/skaffold-linux-amd64
        chmod +x skaffold && sudo mv skaffold /usr/local/bin
        skaffold version

    - name: Build & Push
      run: skaffold build --default-repo '${{ env.GOOGLECLOUD_REGION}}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-apps' --push --file-output build.out

    - name: Archive the build result
      uses: actions/upload-artifact@v2
      with:
        name: build-result
        path: build.out

    - name: Make a release
      run: gcloud deploy releases create "git-${GITHUB_SHA::7}" --region ${{ env.GOOGLECLOUD_REGION }} --delivery-pipeline ${{ env.DELIVERY_PIPELINE }} --build-artifacts build.out --annotations "commitId=${GITHUB_SHA},author=${GITHUB_ACTOR},date=$(date '+%Y-%m-%d %H:%M:%S')"
