name: Release

on:
  push:
    branches:
      - main

env:
  GOOGLECLOUD_REGION: "asia-northeast1"

jobs:
  test-web-code:
    name: Test Web code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42
        args: --verbose
        working-directory: src/web
        skip-go-installation: true

  test-api-code:
    name: Test API code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42
        args: --verbose
        working-directory: src/api
        skip-go-installation: true

  test-template:
    name: Test templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold && sudo mv skaffold /usr/local/bin
        skaffold version
    - name: Rendering
      run: |
        skaffold render --digest-source='none' -o local.yaml --profile local
    - name: Archive the rendered templates
      uses: actions/upload-artifact@v2
      with:
        name: rendered-templates
        path: |
          local.yaml
    - name: Kubeval k8s manifests
      uses: azure/k8s-lint@v1
      with:
        manifests: |
          local.yaml

  release:
    name: Release
    needs: 
      - test-web-code
      - test-api-code
      - test-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GOOGLECLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLECLOUD_SA_KEY }}
        export_default_credentials: true

    - name: Setup credential helper
      run: gcloud auth configure-docker "${{ env.GOOGLECLOUD_REGION}}-docker.pkg.dev"

    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold && sudo mv skaffold /usr/local/bin
        skaffold version

    - name: Build & Push
      run: skaffold build --default-repo '${{ env.GOOGLECLOUD_REGION}}-docker.pkg.dev/${{ secrets.GOOGLECLOUD_PROJECT_ID }}/cd-test' --push --file-output=build.out

    - name: Archive the build result
      uses: actions/upload-artifact@v2
      with:
        name: build-result
        path: |
          build.out
