apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: app
    context: src
manifests:
  rawYaml:
  - deploy/k8s/dev/*
deploy:
  kubectl: {}
profiles:
- name: prod
  manifests:
    rawYaml:
    - deploy/k8s/prod/*
