apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: k8s-pipeline
serialPipeline:
  stages:
  - targetId: dev
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
gke:
  cluster: projects/rnak-altostrat/locations/asia-northeast1/clusters/my-gke
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
gke:
  cluster: projects/rnak-altostrat/locations/asia-northeast1/clusters/my-gke
