kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  template:
    spec:
      containers:
      - name: main
        env:
        - name: LOG_LEVEL
          value: "info"
