name: Test

on: pull_request

jobs:
  test-code:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dart lang
      uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get
      working-directory: src
    - name: Verify formatting
      run: dart format — output=none — set-exit-if-changed .
      working-directory: src
    - name: Analyze project source
      run: dart analyze
      working-directory: src
    - name: Run tests
      run: dart test
      working-directory: src

  test-template:
    name: Test templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Kubeval k8s manifests
      uses: azure/k8s-lint@v2.0
      with:
        manifests: |
          deploy/k8s/dev/web.yaml
          deploy/k8s/prod/web.yaml
