name: Promotion

on:
  push:
    tags:
    - prod-*

env:
  GOOGLECLOUD_REGION: "asia-northeast1"
  DELIVERY_PIPELINE: "k8s-pipeline"

jobs:
  promotion:
    name: Promotion
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLECLOUD_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Promote a release
      run: gcloud deploy releases promote --release "git-${GITHUB_SHA::7}" --region ${{ env.GOOGLECLOUD_REGION }} --delivery-pipeline ${{ env.DELIVERY_PIPELINE }} --annotations "tag=${GITHUB_REF#refs/tags/},author=${GITHUB_ACTOR},date=$(date '+%Y-%m-%d %H:%M:%S')"
